<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/joemccarney/Documents/img/blender/wunderkammer/AppleDesktop.glb -s -u -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  export const ref = new Group()

  const suspend = useSuspense()

  const gltf = suspend(useGltf('/models/AppleDesktop-transformed.glb', { useDraco: true }))

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Object_10.geometry} material={gltf.materials.light_beige} />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_11.geometry}
        material={gltf.materials.light_beige}
      />

      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.dark_beige} />
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Object_5.geometry} material={gltf.materials.dark_grey} />
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.darker_beige} />
      <T.Mesh castShadow receiveShadow geometry={gltf.nodes.Object_7.geometry} material={gltf.materials.darker_beige} />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_8.geometry}
        material={gltf.materials.darkest_beige}
      />
      <T.Mesh
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_9.geometry}
        material={gltf.materials.darkest_beige}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
