<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/joemccarney/Documents/img/blender/wunderkammer/Keyboard.glb -s -u -k -T
-->

<script>
	import * as THREE from 'three';
	import { T, forwardEventHandlers, watch } from '@threlte/core';
	import { useGltf, useSuspense, interactivity, Float, MeshRefractionMaterial } from '@threlte/extras';
	import { spring } from 'svelte/motion';
	import { onDestroy, onMount } from 'svelte';
	import { writable } from 'svelte/store';
	import Sound from '../utils/Sound.js';
	
	let sound;
	export const ref = new THREE.Group();
	interactivity();

	const gltf = useGltf('/models/Keyboard-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
	const pink = new THREE.Color(0xF286C4);

	const white = new THREE.MeshStandardMaterial({ color: 'white' });
	const black = new THREE.MeshStandardMaterial({ color: 'black' });
	const pinkMat = new THREE.MeshPhysicalMaterial({
    color: pink,
    reflectivity: 1,
    metalness: 0.9,
    roughness: 0.2
  })
  const scale = spring(1)

  const onPointerEnter = () => {
    material.color = blue
    scale.set(1.01)
  }
  const onPointerLeave = () => {
    material.color = red
    scale.set(1)
  }
	const notes = ['F', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E'];

	export let rotations = {};
	let currentRotation = writable({});

	function getRotations() {
		let cycleCount = 1;

		for (let i = 0; i < 31; i++) {
			const note = notes[i % notes.length];

			if (note === 'C' && i !== 0) {
				cycleCount++;
			}

			const key = `${note}${cycleCount}`;

			rotations[key] = spring(0, { stiffness: 0.1, damping: 0.5 });
			rotations[key].subscribe((value) => {
				currentRotation.update((cr) => ({ ...cr, [key]: value }));
			});
		}
	}

	function handleClick(id) {
		if (rotations[id]) {
			rotations[id].set(-0.1);
			sound.startPlayback(id);
		}
	}

	function handleRelease(id) {
		if (rotations[id]) {
			rotations[id].set(0);
			sound.stopPlayback();
		}
	}
	watch(currentRotation, ($currentRotation) => {
	
		return () => {
			console.log('cleanup');
		};
	});

	onMount(() => {
		getRotations();
		sound = new Sound();
	});
	onDestroy(() => {
		Object.values(rotations).forEach((spring) => spring.set(0));
	});
</script>



<T
	is={ref}
	dispose={false}
	{...$$restProps}
	bind:this={$component}
	scale={0.01}
	position.y={0.5}
  position.x={2}
	rotation.y={Math.PI / 2}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
	<Float
  floatIntensity={5}
  scale={$scale}
  rotationIntensity={2}
  rotationSpeed={[1, 0.5, 0.2]}
>
		<T.Mesh
			name="B1"
			castShadow
			receiveShadow
			geometry={gltf.nodes.B1.geometry}
			material={white}
			position={[15.53, 5.83, 7.55]}
			rotation={[$currentRotation['B1'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>

		<T.Mesh
			name="G1"
			castShadow
			receiveShadow
			geometry={gltf.nodes.G1.geometry}
			material={white}
			position={[21.93, 5.83, 7.55]}
			rotation={[$currentRotation['G1'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="F1"
			castShadow
			receiveShadow
			geometry={gltf.nodes.F1.geometry}
			material={white}
			position={[25.43, 5.83, 7.55]}
			rotation={[$currentRotation['F1'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="C2"
			castShadow
			receiveShadow
			geometry={gltf.nodes.C2.geometry}
			material={white}
			position={[13.52, 5.83, 7.55]}
			rotation={[$currentRotation['C2'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="D2"
			castShadow
			receiveShadow
			geometry={gltf.nodes.D2.geometry}
			material={white}
			position={[9.93, 5.83, 7.55]}
			rotation={[$currentRotation['D2'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="D3"
			castShadow
			receiveShadow
			geometry={gltf.nodes.D3.geometry}
			material={white}
			position={[-10.63, 5.83, 7.55]}
			rotation={[$currentRotation['D3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="E2"
			castShadow
			receiveShadow
			geometry={gltf.nodes.E2.geometry}
			material={white}
			position={[6.53, 5.83, 7.55]}
			rotation={[$currentRotation['E2'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="E3"
			castShadow
			receiveShadow
			geometry={gltf.nodes.E3.geometry}
			material={white}
			position={[-14.03, 5.83, 7.55]}
			rotation={[$currentRotation['E3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="B2"
			castShadow
			receiveShadow
			geometry={gltf.nodes.B2.geometry}
			material={white}
			position={[-5.07, 5.83, 7.55]}
			rotation={[$currentRotation['B2'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="B3"
			castShadow
			receiveShadow
			geometry={gltf.nodes.B3.geometry}
			material={white}
			position={[-25.63, 5.83, 7.55]}
			rotation={[$currentRotation['B3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="G2"
			castShadow
			receiveShadow
			geometry={gltf.nodes.G2.geometry}
			material={white}
			position={[1.13, 5.83, 7.55]}
			rotation={[$currentRotation['G2'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="G3"
			castShadow
			receiveShadow
			geometry={gltf.nodes.G3.geometry}
			material={white}
			position={[-19.43, 5.83, 7.55]}
			rotation={[$currentRotation['G3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="A1"
			castShadow
			receiveShadow
			geometry={gltf.nodes.A1.geometry}
			material={white}
			position={[18.75, 5.83, 7.55]}
			rotation={[$currentRotation['A1'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="F2"
			castShadow
			receiveShadow
			geometry={gltf.nodes.F2.geometry}
			material={white}
			position={[4.73, 5.83, 7.55]}
			rotation={[$currentRotation['F2'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="F3"
			castShadow
			receiveShadow
			geometry={gltf.nodes.F3.geometry}
			material={white}
			position={[-15.83, 5.83, 7.55]}
			rotation={[$currentRotation['F3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="A2"
			castShadow
			receiveShadow
			geometry={gltf.nodes.A2.geometry}
			material={white}
			position={[-1.87, 5.83, 7.55]}
			rotation={[$currentRotation['A2'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="A3"
			castShadow
			receiveShadow
			geometry={gltf.nodes.A3.geometry}
			material={white}
			position={[-22.43, 5.83, 7.55]}
			rotation={[$currentRotation['A3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="C3"
			castShadow
			receiveShadow
			geometry={gltf.nodes.C3.geometry}
			material={white}
			position={[-6.83, 5.83, 7.55]}
			rotation={[$currentRotation['C3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="Cylinder"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Cylinder.geometry}
			material={pinkMat}
			on:pointerenter={onPointerEnter}
			on:pointerleave={onPointerLeave}
			position={[0.14, -0, 9.92]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="F#1"
			castShadow
			receiveShadow
			geometry={gltf.nodes['F#1'].geometry}
			material={black}
			position={[23.43, 5.83, 7.55]}
			rotation={[$currentRotation['F#1'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="C#"
			castShadow
			receiveShadow
			geometry={gltf.nodes['C#'].geometry}
			material={black}
			position={[11.67, 5.83, 7.55]}
			rotation={[$currentRotation['C#1'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="C#3"
			castShadow
			receiveShadow
			geometry={gltf.nodes['C#3'].geometry}
			material={black}
			position={[-9.03, 5.83, 7.55]}
			rotation={[$currentRotation['C#3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="D#2"
			castShadow
			receiveShadow
			geometry={gltf.nodes['D#2'].geometry}
			material={black}
			position={[8.33, 5.83, 7.55]}
			rotation={[$currentRotation['D#2'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="D#3"
			castShadow
			receiveShadow
			geometry={gltf.nodes['D#3'].geometry}
			material={black}
			position={[-12.23, 5.83, 7.55]}
			rotation={[$currentRotation['D#3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="F#2"
			castShadow
			receiveShadow
			geometry={gltf.nodes['F#2'].geometry}
			material={black}
			position={[2.73, 5.83, 7.55]}
			rotation={[$currentRotation['F#2'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="F#3"
			castShadow
			receiveShadow
			geometry={gltf.nodes['F#3'].geometry}
			material={black}
			position={[-17.83, 5.83, 7.55]}
			rotation={[$currentRotation['F#3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="G#1"
			castShadow
			receiveShadow
			geometry={gltf.nodes['G#1'].geometry}
			material={black}
			position={[20.35, 5.83, 7.55]}
			rotation={[$currentRotation['G#1'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="G#2"
			castShadow
			receiveShadow
			geometry={gltf.nodes['G#2'].geometry}
			material={black}
			position={[-0.67, 5.83, 7.55]}
			rotation={[$currentRotation['G#2'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="G#3"
			castShadow
			receiveShadow
			geometry={gltf.nodes['G#3'].geometry}
			material={black}
			position={[-21.23, 5.83, 7.55]}
			rotation={[$currentRotation['G#3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="A#1"
			castShadow
			receiveShadow
			geometry={gltf.nodes['A#1'].geometry}
			material={black}
			position={[16.95, 5.83, 7.55]}
			rotation={[$currentRotation['A#1'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="A#2"
			castShadow
			receiveShadow
			geometry={gltf.nodes['A#2'].geometry}
			material={black}
			position={[-3.27, 5.83, 7.55]}
			rotation={[$currentRotation['A#2'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
		<T.Mesh
			name="A#3"
			castShadow
			receiveShadow
			geometry={gltf.nodes['A#3'].geometry}
			material={black}
			position={[-23.83, 5.83, 7.55]}
			rotation={[$currentRotation['A#3'] || 0, 0, 0]}
			on:pointerdown={(e) => handleClick(e.object.name)}
			on:pointerup={(e) => handleRelease(e.object.name)}
			on:pointerout={(e) => handleRelease(e.object.name)}
		/>
	</Float>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
