<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/joemccarney/Documents/img/blender/wunderkammer/Room.glb -s -T -u -k
-->

<script>
	import * as THREE from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useSuspense } from '@threlte/extras';

	export const ref = new THREE.Group();

	const suspend = useSuspense();

	const gltf = suspend(useGltf('/models/Room-transformed.glb', { useDraco: true }));

	const component = forwardEventHandlers();

	const white = new THREE.MeshStandardMaterial({ color: 'white' })
	const blue = new THREE.MeshStandardMaterial({color: 'skyblue'})

</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			name="Cube"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Cube.geometry}
			material={white}
		/>
		<T.Mesh
			name="Outer_Pane"
			castShadow
			receiveShadow
			geometry={gltf.nodes.Outer_Pane.geometry}
			material={blue}
			position={[2.1, 4, -5.04]}
			rotation={[0, Math.PI / 2, 0]}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
