<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/joemccarney/Documents/img/blender/wunderkammer/scene.glb -s -u -T
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useSuspense } from '@threlte/extras';

	export const ref = new Group();

	const suspend = useSuspense();

	const gltf = suspend(useGltf('/models/scene-transformed.glb', { useDraco: true }));

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[0.69, 0.18, -2.95]}>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Brass_Wheels_0.geometry}
				material={gltf.materials['Brass.001']}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Legs_and_Rails_0.geometry}
				material={gltf.materials.Mahogany_Sides_and_Legs}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Table_Top_0.geometry}
				material={gltf.materials['Mahogany_Top.001']}
				position={[0, 2.44, 0]}
			/>
		</T.Group>
		<T.Mesh
			castShadow
			receiveShadow
			geometry={gltf.nodes.Cube.geometry}
			material={gltf.nodes.Cube.material}
			scale={[1, 0.04, 1]}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
