<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/Room.glb -s -T -k
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/Room-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} position.y={-2}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      name="Cube_Baked"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube_Baked.geometry}
      material={gltf.materials['Cube_Baked.002']}
      position={[-5.27, 1.1, 12.68]}
    />
    <T.Mesh
      name="Frame_Baked"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Frame_Baked.geometry}
      material={gltf.materials['Frame_Baked.002']}
      position={[7.37, 25.26, -17.72]}
      rotation={[0, Math.PI / 2, 0]}
      scale={6.03}
    />
    <T.Mesh
      name="Pane_Baked"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Pane_Baked.geometry}
      material={gltf.materials['Pane_Baked.002']}
      position={[7.37, 25.26, -17.72]}
      rotation={[0, Math.PI / 2, 0]}
      scale={6.03}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
