<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/joemccarney/Documents/img/blender/wunderkammer/cabinet.glb -T -u -k
-->

<script>
	import * as THREE from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { onMount, onDestroy } from 'svelte';
	import { wunderkammerRef, propsState } from '../utils/stores.js';
	import {
		useGltf,
		useGltfAnimations,
		useSuspense,
		useCursor,
		interactivity
	} from '@threlte/extras';
	interactivity();
	const { hovering, onPointerEnter, onPointerLeave } = useCursor();
	export const ref = new THREE.Group();

	const suspend = useSuspense();

	const gltf = suspend(useGltf('/models/cabinet-transformed.glb', { useDraco: true }));
	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	const component = forwardEventHandlers();

	export const triggerAnimation = () => {
		const cabinetActionL = $actions['Open Left'];
		const cabinetActionR = $actions['Open Right'];
		if (cabinetActionL && cabinetActionR) {
			cabinetActionL.loop = THREE.LoopOnce;
			cabinetActionR.loop = THREE.LoopOnce;
			cabinetActionL.clampWhenFinished = true;
			cabinetActionR.clampWhenFinished = true;
			if ($propsState.doorsOpen === true) {
				cabinetActionL.timeScale = -cabinetActionL.timeScale;
				cabinetActionR.timeScale = -cabinetActionR.timeScale;
			} else if ($propsState.doorsOpen === false) {
				cabinetActionL.timeScale = cabinetActionL.timeScale;
				cabinetActionR.timeScale = cabinetActionR.timeScale;
			}
			cabinetActionL.paused = false;
			cabinetActionR.paused = false;
			cabinetActionR.play();
			cabinetActionL.play();
		}
	};

	onMount(() => {
		wunderkammerRef.set(ref);
	});
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene" scale={0.15} position={[-1, 0, -4]}>
			<T.Mesh
				name="Cabinet_Baked"
				geometry={gltf.nodes.Cabinet_Baked.geometry}
				material={gltf.materials.Cabinet_Baked}
			/>
			<T.Mesh
				name="Door_L_Baked"
				geometry={gltf.nodes.Door_L_Baked.geometry}
				material={gltf.materials['Door L_Baked']}
				position={[-9.36, 18.45, 13.7]}
				on:pointerenter={onPointerEnter}
				on:pointerleave={onPointerLeave}
				on:click={triggerAnimation}
			/>
			<T.Mesh
				name="Door_R_Baked"
				geometry={gltf.nodes.Door_R_Baked.geometry}
				material={gltf.materials['Door R_Baked']}
				position={[8.89, 18.24, 14.07]}
				on:pointerenter={onPointerEnter}
				on:pointerleave={onPointerLeave}
				on:click={triggerAnimation}
			/>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
