<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/Lever.glb -T -u -k
-->

<script>
	import * as THREE from 'three';
	import { createTransition } from '@threlte/extras';
	import { cubicOut } from 'svelte/easing';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations, useSuspense } from '@threlte/extras';

	export const ref = new THREE.Group();

	const suspend = useSuspense();

	const gltf = suspend(useGltf('/models/Lever-transformed.glb', { useDraco: true }));
	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	const component = forwardEventHandlers();
	let leverMetal = new THREE.MeshStandardMaterial({
		roughness: 0.05,
		metalness: 1
	});
	let plastic = new THREE.MeshStandardMaterial({
		roughness: 0.05,
		metalness: 0.4,
		color: 0xff0000
	});
	const fly = createTransition((ref) => {
		const startY = 1000
		const endY = 0
		return {
			tick(t) {
				t = 1 - t;
				ref.position.y = startY + (endY - startY) * (1 - t)
				
			},
			easing: cubicOut,
			duration: 5000
		};
	});
	export const triggerAnimation = () => {
		const crankAction = $actions['Crank'];

		if (crankAction) {
			crankAction.loop = THREE.LoopOnce;
			crankAction.clampWhenFinished = true;

			crankAction.paused = false;

			crankAction.play();
		}
	};
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component} in={fly} scale={80}  >
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="Handle_component" position={[-0.01, 0.21, 0.3]} rotation={[-0.49, 0, 0]}>
				<T.Mesh
					name="Handle_Geometry"
					geometry={gltf.nodes.Handle_Geometry.geometry}
					material={leverMetal}
					position={[0.01, 0.66, 0.4]}
					on:click={triggerAnimation}
				/>
			</T.Group>
			<T.Mesh
				name="Base"
				geometry={gltf.nodes.Base.geometry}
				material={plastic}
				position={[0, 0.3, -0.21]}
			/>
			<T.Mesh
				name="Shaft"
				geometry={gltf.nodes.Shaft.geometry}
				material={leverMetal}
				position={[0, 0.3, -0.21]}
			/>
			<T.Mesh
				name="Shaft-Base"
				geometry={gltf.nodes['Shaft-Base'].geometry}
				material={leverMetal}
				position={[0, 0.3, -0.21]}
			/>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
